### ISSUE TITLE
Panic when deleting

### ISSUE THREAD

**Issue by metalmatze** [digitalocean/csi-digitalocean#33]
Hey, I already have 180 restarts on my pod `csi-provisioner-doplugin-0`.

Here are the logs:
```
time="2018-05-26T16:01:21Z" level=info msg="get plugin info called" method=get_plugin_info node_id=94784XXX region=fra1 response="name:\"com.digitalocean.csi.dobs\" vendor_version:\"0.1.0\" "
time="2018-05-26T16:01:21Z" level=info msg="delete volume called" method=delete_volume node_id=94784XXX region=fra1 volume_id=252ec68a-4664-11e8-9dc3-0242ac110XXX
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c8e35]

goroutine 32 [running]:
github.com/digitalocean/csi-digitalocean/driver.(*Driver).DeleteVolume(0xc420094900, 0x94f040, 0xc4201b24e0, 0xc420170760, 0xc420094900, 0x0, 0x0)
	/Users/fatih/go/src/github.com/digitalocean/csi-digitalocean/driver/controller.go:152 +0x335
github.com/digitalocean/csi-digitalocean/vendor/github.com/container-storage-interface/spec/lib/go/csi/v0._Controller_DeleteVolume_Handler.func1(0x94f040, 0xc4201b24e0, 0x88a220, 0xc420170760, 0x7fbaabe886c8, 0x0, 0x8a7ac0, 0xc420170740)
	/Users/fatih/go/src/github.com/digitalocean/csi-digitalocean/vendor/github.com/container-storage-interface/spec/lib/go/csi/v0/csi.pb.go:2148 +0x86
github.com/digitalocean/csi-digitalocean/driver.(*Driver).Run.func1(0x94f040, 0xc4201b24e0, 0x88a220, 0xc420170760, 0xc420170780, 0xc4201707a0, 0x853ca0, 0xbe0bc8, 0x8d0260, 0xc4204112c0)
	/Users/fatih/go/src/github.com/digitalocean/csi-digitalocean/driver/driver.go:129 +0x78
github.com/digitalocean/csi-digitalocean/vendor/github.com/container-storage-interface/spec/lib/go/csi/v0._Controller_DeleteVolume_Handler(0x8cfbe0, 0xc420094900, 0x94f040, 0xc4201b24e0, 0xc4201822a0, 0xc4200771c0, 0x0, 0x0, 0x267d01a97ab537a3, 0x1bfdf1598e0ef9d6)
	/Users/fatih/go/src/github.com/digitalocean/csi-digitalocean/vendor/github.com/container-storage-interface/spec/lib/go/csi/v0/csi.pb.go:2150 +0x167
github.com/digitalocean/csi-digitalocean/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200d5600, 0x9507a0, 0xc420001200, 0xc4204112c0, 0xc4201b26f0, 0xbb92f8, 0x0, 0x0, 0x0)
	/Users/fatih/go/src/github.com/digitalocean/csi-digitalocean/vendor/google.golang.org/grpc/server.go:923 +0x889
github.com/digitalocean/csi-digitalocean/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200d5600, 0x9507a0, 0xc420001200, 0xc4204112c0, 0x0)
	/Users/fatih/go/src/github.com/digitalocean/csi-digitalocean/vendor/google.golang.org/grpc/server.go:1148 +0x1318
github.com/digitalocean/csi-digitalocean/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42002a040, 0xc4200d5600, 0x9507a0, 0xc420001200, 0xc4204112c0)
	/Users/fatih/go/src/github.com/digitalocean/csi-digitalocean/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/digitalocean/csi-digitalocean/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/fatih/go/src/github.com/digitalocean/csi-digitalocean/vendor/google.golang.org/grpc/server.go:635 +0xa1
```

I can send you the `node_id` or `volume_id` via Slack, in case you need them. I don't think so.

**Comment by fatih** [comment]
Thanks for the report @metalmatze. This is fixed with #34. I released a new version `v0.1.1` https://github.com/digitalocean/csi-digitalocean/releases/tag/v0.1.1 (also see https://hub.docker.com/r/digitalocean/do-csi-plugin/tags/). There is a new file under `deploy/kubernetes` which you can use.
